-- CreateEnum
CREATE TYPE "Cart_status" AS ENUM ('EM_PROCESSAMENTO', 'EM_TRANSITO', 'ENTREGUE', 'EM_TROCA', 'TROCA_AUTORIZADA', 'REPROVADA');

-- AlterTable
ALTER TABLE "carts" ADD COLUMN     "status" "Cart_status" NOT NULL DEFAULT 'EM_PROCESSAMENTO';
